services:

  # VENDORS
  # -------

  # DB
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data
    env_file:
      - ./configs/dev/.env
      - ./configs/dev/mongo/.env
      
  # APP
  # ---

  pizi-server:
    build:
      context: ./
    env_file:
      - ./configs/dev/.env
      - ./configs/dev/pizi-server/.env
    ports:
      - "2200:2200"
      - "9229:9229"
    command:
      - node
      - "--inspect=0.0.0.0"
      - "--experimental-specifier-resolution=node"
      - "./server"
     

  # UTILITIES
  # ---------

  # DB UI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./configs/dev/.env
      - ./configs/dev/mongo-express/.env

  # OPEN API
  swagger-ui:
    image: swaggerapi/swagger-ui
    platform: linux/amd64
    ports:
      - 8082:8080
    volumes:
      - ./docs/api/build/pizi-server.yaml:/pizi-server.yaml
    env_file:
      - ./configs/dev/swagger-ui/.env

volumes:
  mongodb: ~