version: "3.8"

services:
    nodejs:
        image: node:12-alpine
        ports: 
            - "8087:8087"
        working_dir: /app
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        environment:
            PORT: 8087
        command: sh -c "npm install && npm run startNodemon"

    mongo:
        image: mongo
        volumes:
            - 'mongodb:/data/db'

volumes: 
    mongodb:
    node_modules: